# Generated by Django 5.0.4 on 2024-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderm', '0002_remove_item_name_remove_item_price_remove_item_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant_compare_at_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
