# Generated by Django 5.0.4 on 2024-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderm', '0003_alter_item_variant_compare_at_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant_grams',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='variant_inventory_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
