# Generated by Django 5.0.4 on 2024-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderm', '0004_alter_item_variant_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
