# Generated by Django 5.0.6 on 2024-06-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderm', '0005_alter_item_variant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='option1_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option1_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option2_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option2_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option3_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option3_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_compare_at_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_fulfillment_service',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_grams',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_inventory_policy',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_inventory_qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_inventory_tracker',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant_sku',
        ),
    ]
